### ISSUE TITLE
Feat: support share

### ISSUE THREAD

**Issue by imuxin** [imuxin/kubectl-watch#12]
The watched resources are going to be stored into `configmap`.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k8s.io/created-by: kubectl-watch
  generateName:: kubectl-watch-$ResourceType-
  namespace: default
data:
  type: "" # oneof: text,gzip
  log: ""
```
