### ISSUE TITLE
kube-watch script panics

### ISSUE THREAD

**Issue by twuyts** [imuxin/kubectl-watch#14]
I tried to run the kubectl-watch script, but _without_ sudo
It crashed with
```
thread 'main' panicked at 'auth error: unable to run auth exec: No such file or directory (os error 2)', kubectl-watch/src/main.rs:20:13
```
I don't know if this is related to not having root rights (and I'm not going to try), but the question is why does it need them in the first place?

**Comment by imuxin** [comment]
Hi @twuyts, I guess you used [exec command](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins) in the `~/.kube/config`. For example:

```yaml
apiVersion: v1
kind: Config
users:
- name: my-user
  user:
    exec:
      # Command to execute. Required.
      command: "example-cred-plugin"
...
```

kubectl-watch script executes kubectl-watch binary in the **container**. But your cred plugin binary was in the host machine. Could you edit the script and add some config like `-v /path/to/example-cred-plugin:/usr/local/bin/example-cred-plugin`, so that kubectl-watch can find the command in the container.
